# -*- coding: utf-8 -*-
"""2. Reading Data from multiple Excel files using python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzu5RUAPJS9_Y1QryaqvE926WaXRInYC
"""

# Code to read csv file into colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1RbG76av_2kFXsKv_RstsC3PTmSXkcPp9'}) # replace the id with id of file you want to access
downloaded.GetContentFile('SampleData.xlsx')

downloaded = drive.CreateFile({'id':'1Jet3cbsqydsYwktspbIsscFl250BTRQU'}) # replace the id with id of file you want to access
downloaded.GetContentFile('SampleData3.xlsx')

import xlrd

path1 = "SampleData.xlsx"
path2 = "SampleData3.xlsx"

inputWorkbook1 = xlrd.open_workbook(path1)
inputWorksheet1 = inputWorkbook1.sheet_by_index(0)
inputWorkbook2 = xlrd.open_workbook(path2)
inputWorksheet2 = inputWorkbook2.sheet_by_index(0)

rep = list()
item = list()
c = 2
d = 2
n = 1
while n <= a-2:
  e = inputWorksheet1.cell_value(c,d)
  rep.append(e)
  n += 1
  c += 1
  if n == 44:
    c = 2
    d = 4
    n = 1
    while n<= a-2:
      e = inputWorksheet2.cell_value(c,d)
      item.append(e)
      n += 1
      c += 1
      if n == 44:
        break
      else:
        continue
  else:
    continue
x = 0
while x != len(rep):
  print(x, rep[x], "|", item[x])
  x += 1

