# -*- coding: utf-8 -*-
"""5. Merging columns from different excel files into one single excel file using Pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzu5RUAPJS9_Y1QryaqvE926WaXRInYC
"""

# Code to read csv file into colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1RbG76av_2kFXsKv_RstsC3PTmSXkcPp9'}) # replace the id with id of file you want to access
downloaded.GetContentFile('SampleData.xlsx')

downloaded = drive.CreateFile({'id':'10xUlClZ2xbfFLrwUl40HAe4ELOvJV2BO'}) # replace the id with id of file you want to access
downloaded.GetContentFile('SampleData3.xlsx')

downloaded = drive.CreateFile({'id':'10xUlClZ2xbfFLrwUl40HAe4ELOvJV2BO'}) # replace the id with id of file you want to access
downloaded.GetContentFile('SampleData4.xlsx')

import pandas as pd

path0 = "SampleData.xlsx"
path1 = "SampleData3.xlsx"
path2 = "SampleData4.xlsx"

df0 = pd.read_excel(path0)
df1 = pd.read_excel(path1)
df2 = pd.read_excel(path2)

values0 = df0[['Rep']]
values1 = df1[['Units']]
values2 = df2[['Total']]

dataframes = [values0, values1, values2]
join = pd.concat(dataframes, axis = 1 ,ignore_index=True)
join.to_excel("output_final.xlsx")

