# -*- coding: utf-8 -*-
"""0. Reading and entire Excel files using pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzu5RUAPJS9_Y1QryaqvE926WaXRInYC
"""

# Code to read csv file into colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'10xUlClZ2xbfFLrwUl40HAe4ELOvJV2BO'}) # replace the id with id of file you want to access
downloaded.GetContentFile('SampleData4.xlsx')

import pandas as pd
path1 = "SampleData.xlsx"
df1 = pd.read_excel(path1)

print(df1)

