# -*- coding: utf-8 -*-
"""1. Reading Data from a single Excel file using python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzu5RUAPJS9_Y1QryaqvE926WaXRInYC
"""

# Code to read csv file into colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1RbG76av_2kFXsKv_RstsC3PTmSXkcPp9'}) # replace the id with id of file you want to access
downloaded.GetContentFile('SampleData.xlsx')

import xlrd
path = "SampleData.xlsx"
inputWorkbook = xlrd.open_workbook(path)
inputWorksheet = inputWorkbook.sheet_by_index(0)
a = inputWorksheet.nrows
b = inputWorksheet.ncols
rep = list()
item = list()
c = 2
d = 2
n = 1
while n <= a-2:
  e = inputWorksheet.cell_value(c,d)
  rep.append(e)
  n += 1
  c += 1
  if n == 44:
    c = 2
    d = 3
    n = 1
    while n<= a-2:
      e = inputWorksheet.cell_value(c,d)
      item.append(e)
      n += 1
      c += 1
      if n == 44:
        break
      else:
        continue
  else:
    continue
x = 0
while x != len(rep):
  print(x, rep[x], "|", item[x])
  x += 1

